# -*- coding: utf-8 -*-
"""normalize_classes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MGcgqSx4HUzt3n8swUTXk0cj6kJ7Bavc
"""

import polars as pl
from PIL import Image
import io

# Lê o parquet
df = pl.read_parquet("/content/drive/MyDrive/UFRGS/TCC/dados/dataset_alzheimer_unificado.parquet")

# Verifica metadados
print("Label", df["label"][0])
print("Classe", df["class_name"][0])

# Verifica algumas linhas
print(df.select(["label", "class_name", "source"]).head(10))

# Valores únicos em cada coluna
print("Label únicos", df["label"].unique().to_list())
print("Classes únicas", df["class_name"].unique().to_list())
print("Sources únicos", df["source"].unique().to_list())

class_counts = df.group_by("class_name").count()
print(class_counts)

# Normaliza class_name (substitui espaços por underscore e deixa tudo igual)
df = df.with_columns(
    pl.col("class_name")
    .str.replace_all(" ", "_")   # troca espaço por "_"
    .str.to_lowercase()          # coloca tudo minúsculo
    .alias("class_name")
)

# Reconta
class_counts = df.group_by("class_name").len()
print(class_counts)